using System;
using System.Text;

namespace LightyDesign.Generator;

internal sealed class CodeWriter
{
    private readonly StringBuilder _builder = new();
    private int _indentLevel;

    public void Indent() => _indentLevel += 1;

    public void Outdent() => _indentLevel = Math.Max(0, _indentLevel - 1);

    public void AppendLine(string value = "")
    {
        if (value.Length > 0)
        {
            _builder.Append(new string(' ', _indentLevel * 4));
            _builder.AppendLine(value);
            return;
        }

        _builder.AppendLine();
    }

    public void Append(string value)
    {
        var lines = value.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
        foreach (var line in lines)
        {
            if (line.Length == 0)
            {
                _builder.AppendLine();
                continue;
            }

            _builder.Append(new string(' ', _indentLevel * 4));
            _builder.AppendLine(line);
        }
    }

    public void AppendAutoGeneratedHeader()
    {
        AppendLine("//------------------------------------------------------------------------------");
        AppendLine("// <auto-generated>");
        AppendLine("//     此文件由代码生成器生成，请勿修改。");
        AppendLine("//     This file is generated by a tool. Do not modify.");
        AppendLine("// </auto-generated>");
        AppendLine("//------------------------------------------------------------------------------");
        AppendLine();
    }

    public override string ToString() => _builder.ToString();
}
